updated sesamessh

diff --git a/sesamessh b/sesamessh
--- a/sesamessh
+++ b/sesamessh
@@ -3,8 +3,8 @@
 # This is free software, GNU GPL >=2.0. There is NO WARRANTY. Use at your risk.
 #
 # $ curl -s https://pts.github.io/sesamessh | sh
-# $ curl -Ls https://github.com/pts/sesamessh/raw/master/sesamessh | sh
-# $ wget -q -O- https://github.com/pts/sesamessh/raw/master/sesamessh | sh
+# $ curl -Ls  https://github.com/pts/sesamessh/raw/master/sesamessh | sh
+# $ wget -qO- https://github.com/pts/sesamessh/raw/master/sesamessh | sh
 # $ busybox wget -qO- http://pts.github.io/sesamessh | busybox sh
 #
 
@@ -21,10 +21,15 @@ die() {
 # Needed in $SHCK_ARGS below.
 test "$ZSH_VERSION" && setopt shwordsplit 2>/dev/null
 
-unset TARGET UK HK IS_SETUP STATUS EXPECTED_OUTPUT PYCODE ARG SHKC_ARGS Q_ARGS  # Unexport.
+unset TARGET UK HK IS_SETUP IS_RANDOM_UK IS_RANDOM STATUS EXPECTED_OUTPUT PYCODE ARG SHKC_ARGS Q_ARGS  # Unexport.
 IS_SETUP=
+IS_RANDOM_UK=
 if test "$1" = setup || test "$1" = --setup; then
   IS_SETUP=1
+  shift
+elif test "$1" = setup-random || test "$1" = --setup-random; then
+  IS_SETUP=1
+  IS_RANDOM_UK=1
   shift
 fi
 
@@ -52,7 +57,7 @@ if test $# = 0; then
     IS_SETUP=1
     TARGET="${TARGET#*setup }"
   fi
-  
+
   # Dash and busybox sh don't support this:
   # test -z "$BASH_SOURCE" && test -z "$ZSH_SCRIPT"
   # This is for interactive SSH in `curl ... | sh'
@@ -67,6 +72,11 @@ if test "$SESAMESSH_UK"; then
   # Do this instead: `read SESAMESSH_UK; export SESAMESSH_UK'.
   UK="$SESAMESSH_UK"
   unset SESAMESSH_UK  # Prevent exporting.
+elif test "$IS_RANDOM_UK"; then
+  PYCODE='import base64, os; print base64.b64encode(os.urandom(32))'
+  UK="$("$PYTHON" -c "$PYCODE")"
+  test "$?" = 0 || die 'random user key generation failed'
+  test "${UK%=}" = "$UK" && die "invalid random user key: $UK"
 else
   if test $# != 0; then
     echo -n "Enter sesamessh user key for target $*: " >&2
@@ -171,17 +181,27 @@ def main_pre(uk):
 
   hk = os.getenv("HK", "").strip()
   if hk:
-    host_key = ""
-    if not host_key and hk.startswith("ssh-ed25519"):
+    host_key_line = host_key = ""
+    if not host_key and hk.startswith("ssh-ed25519 "):
       hks = hk.split()
-      assert len(hks) == 3, "Bad host key format: %r" % hk
-      assert hks[0] == "h" and hks[1] == "ssh-ed25519", "Bad host key fields: %r" % hk
+      assert len(hks) in (2, 3), "Bad host key format: %r" % hk
+      assert hks[1] == "ssh-ed25519", "Bad host key fields: %r" % hk
       try:
-        host_key_data = base64.b64decode(hks[2])
+        host_key_data = base64.b64decode(hks[1])
       except (TypeError, ValueError):
         assert 0, "Bad host key syntax: %r" % hk
       assert len(host_key_data) == 51 and host_key_data.startswith("\0\0\0\x0bssh-ed25519\0\0\0 "), "Bad host key encoded format: %r" % hk
       host_key = host_key_data[19:]
+    if not host_key and hk.startswith("ssh-rsa "):
+      hks = hk.split()
+      assert len(hks) in (2, 3), "Bad host key format: %r" % hk
+      assert hks[0] == "ssh-rsa", "Bad host key fields: %r" % hk
+      try:
+        host_key_data = base64.b64decode(hks[1])
+      except (TypeError, ValueError):
+        assert 0, "Bad host key syntax: %r" % hk
+      assert host_key_data.startswith("\0\0\0\7ssh-rsa\0\0"), "Bad host key encoded format: %r" % hk
+      host_key_line = host_key = "ssh-rsa %s" % hks[1]
     if not host_key and len(hk) == 64:
       try:
         host_key = hk.decode("hex")
@@ -196,8 +216,10 @@ def main_pre(uk):
           host_key = ""
       except (TypeError, ValueError):
         host_key = ""
-    assert len(host_key) == 32, "Bad host key: %r" % hk
-    open(tdir + "/known_hosts", "ab").write("h %s\n" % build_openssh_public_key_ed25519(host_key, comment="").rstrip())
+    if not host_key_line:
+      assert len(host_key) == 32, "Bad host key: %r" % hk
+      host_key_line = build_openssh_public_key_ed25519(host_key, comment="").rstrip()
+    open(tdir + "/known_hosts", "ab").write("h %s\n" % host_key_line.rstrip())
 
   assert uk, "Empty user key."
   private_key = ""
@@ -248,21 +270,33 @@ def main_post_setup():
   hk = os.getenv("HK", "").strip()
   hks = hk.split()
   assert len(hks) == 3, "Bad host key format: %r" % hk
-  assert hks[0] == "h" and hks[1] == "ssh-ed25519", "Bad host key fields: %r" % hk
-  try:
-    host_key_data = base64.b64decode(hks[2])
-  except (TypeError, ValueError):
-    assert 0, "Bad host key syntax: %r" % hk
-  assert len(host_key_data) == 51 and host_key_data.startswith("\0\0\0\x0bssh-ed25519\0\0\0 "), "Bad host key encoded format: %r" % hk
-  host_key = host_key_data[19:]
+  assert hks[0] == "h", "Bad hostname in host key: %r" % hk
   tdir = os.getenv("T", "")
-  assert tdir, "Empty tmp dirname."
-  open(tdir + "/id_sesamessh.setup", "wb").write("".join((
-      "info: sesamessh host key b64: %s\n" % base64.b64encode(host_key),
-      "info: sesamessh host key hex: %s\n" % host_key.encode("hex"),
-      "info: sesamessh host public key: %s\n" % build_openssh_public_key_ed25519(host_key, comment="").rstrip(),
-      )))'
-
+  if hks[1] == "ssh-ed25519":
+    try:
+      host_key_data = base64.b64decode(hks[2])
+    except (TypeError, ValueError):
+      assert 0, "Bad host key syntax: %r" % hk
+    assert len(host_key_data) == 51 and host_key_data.startswith("\0\0\0\x0bssh-ed25519\0\0\0 "), "Bad host key encoded format: %r" % hk
+    host_key = host_key_data[19:]
+    assert tdir, "Empty tmp dirname."
+    open(tdir + "/id_sesamessh.setup", "wb").write("".join((
+        "info: sesamessh host key b64: %s\n" % base64.b64encode(host_key),
+        "info: sesamessh host key hex: %s\n" % host_key.encode("hex"),
+        "info: sesamessh host public key: %s\n" % build_openssh_public_key_ed25519(host_key, comment="").rstrip(),
+        )))
+  elif hks[1] == "ssh-rsa":
+    try:
+      host_key_data = base64.b64decode(hks[2])
+    except (TypeError, ValueError):
+      assert 0, "Bad host key syntax: %r" % hk
+    assert host_key_data.startswith("\0\0\0\7ssh-rsa\0\0"), "Bad host key encoded format: %r" % hk
+    open(tdir + "/id_sesamessh.setup", "wb").write("".join((
+        "info: sesamessh host key: ssh-rsa %s\n" % hks[2],
+        )))
+  else:
+    assert 0, "Bad host key fields: %r" % hk
+'
 
 export HK T IS_SETUP
 
@@ -320,7 +354,7 @@ ssh -F/dev/null \
     -o UserKnownHostsFile="$T/known_hosts" \
     -o GlobalKnownHostsFile=/dev/null \
     -o HostKeyAlias=h \
-    -o HostKeyAlgorithms=ssh-ed25519 \
+    -o HostKeyAlgorithms=ssh-ed25519,ssh-rsa \
     -o KexAlgorithms=curve25519-sha256@libssh.org \
     -o IdentitiesOnly=yes \
     -o BatchMode=yes \
